# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_gpio_ext_jp/axi_gpio_ext_jp.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp || ORIG_REF_NAME==axi_gpio_ext_jp} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_processing_system7_0_0/axi_gpio_ext_jp_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_processing_system7_0_0 || ORIG_REF_NAME==axi_gpio_ext_jp_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_0_0/axi_gpio_ext_jp_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_axi_gpio_0_0 || ORIG_REF_NAME==axi_gpio_ext_jp_axi_gpio_0_0} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_1_0/axi_gpio_ext_jp_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_axi_gpio_1_0 || ORIG_REF_NAME==axi_gpio_ext_jp_axi_gpio_1_0} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_axi_gpio_2_0 || ORIG_REF_NAME==axi_gpio_ext_jp_axi_gpio_2_0} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_xbar_0/axi_gpio_ext_jp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_xbar_0 || ORIG_REF_NAME==axi_gpio_ext_jp_xbar_0} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_auto_pc_0/axi_gpio_ext_jp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_auto_pc_0 || ORIG_REF_NAME==axi_gpio_ext_jp_auto_pc_0} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_ps7_0_axi_periph_0/axi_gpio_ext_jp_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_ps7_0_axi_periph_0 || ORIG_REF_NAME==axi_gpio_ext_jp_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_rst_ps7_0_50M_0/axi_gpio_ext_jp_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_ext_jp_rst_ps7_0_50M_0 || ORIG_REF_NAME==axi_gpio_ext_jp_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.gen/sources_1/bd/axi_gpio_ext_jp/axi_gpio_ext_jp_ooc.xdc
