# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.srcs/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0.xci
# IP: The module: 'axi_gpio_ext_jp_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.gen/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_ext_jp_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.gen/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_ext_jp_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.gen/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_ext_jp_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.srcs/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0.xci
# IP: The module: 'axi_gpio_ext_jp_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.gen/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_ext_jp_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.gen/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_ext_jp_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/ECE520/02-AXI_GPIO/axi_gpio_ext_jp/axi_gpio_ext_jp.gen/sources_1/bd/axi_gpio_ext_jp/ip/axi_gpio_ext_jp_axi_gpio_2_0/axi_gpio_ext_jp_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_ext_jp_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
